### ISSUE TITLE
Does not compile on Mac OS X 10.9

### ISSUE THREAD

**Issue by swimchiu** [rcls/crap#8]
$ make
gcc -O2 -Wall -Werror -std=gnu99 -D_GNU_SOURCE -g3 -MMD -MP -MF.deps/cvs_connection.o.d   -c -o cvs_connection.o -c cvs_connection.c
In file included from /opt/local/lib/gcc48/gcc/x86_64-apple-darwin13/4.8.3/include/stdint.h:9:0,
                 from /usr/include/netdb.h:87,
                 from cvs_connection.c:9:
/opt/local/lib/gcc48/gcc/x86_64-apple-darwin13/4.8.3/include-fixed/stdint.h:27:32: fatal error: sys/_types/_int8_t.h: No such file or directory
 #include <sys/_types/_int8_t.h>
                                ^
compilation terminated.
make: **\* [cvs_connection.o] Error 1

**Comment by craigk5n** [comment]
Also does not compile on Mac OS 10.12:

  gcc -O2 -std=c99 -Wall -Wextra -Werror -D_GNU_SOURCE -g3 -MMD -MP -MF.deps/cvs_connection.o.d   -c -o cvs_connection.o -c cvs_connection.c
  cvs_connection.c:10:10: fatal error: 'pipeline.h' file not found
  #include <pipeline.h>
           ^
  1 error generated.
  make: *** [cvs_connection.o] Error 1

**Comment by rcls** [comment]
You would have to install libpipeline on your system. But there are also some linux-isms in my source code. I don't have a Mac but patches to get this going would be welcome. The Linux specific bits are just utility functions etc that should be fairly straightforward to replace.

**Comment by rcls** [comment]
You would have to install libpipeline on your system. But there are also some linux-isms in my source code. I don't have a Mac but patches to get this going would be welcome. The Linux specific bits are just utility functions etc that should be fairly straightforward to replace.
